services:
  postgres:
    container_name: avito-database
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=avito_test
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    restart: always
    networks:
      - avito-network

  avito:
    build:
      context: ./
      dockerfile: cmd/Dockerfile
    container_name: avito-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - avito-network

networks:
  avito-network:

volumes:
  db:
    driver: local