server:
  url: "0.0.0.0:8080"

database:
  host: "avito-database"
  port: 5432
  user: "postgres"
  password: "password"
  dbname: "avito_test"
  sslmode: "disable"

logger:
  sink: "stdout"
  level: "debug"

jwt:
  secret_key: "supersecretkeyforjwt"
  expiration_time: 7200

debug: true